using System;
using System.Collections.Generic;
using System.Linq;

namespace TraductorTipos
{
    public class TraductorTipos
    {
        public static Dictionary<string, string> Tipos { get; set; } = new Dictionary<string, string>()
        {
            { "Car Dealer", "Concesionario De Coches" },
            { "Car Rental", "Alquiler De Coches" },
            { "Car Repair", "Reparacion De Coches" },
            { "Car Wash", "Lavado De Coches" },
            { "Car Dealer Agency", "Concesionario De Coches" },
            { "Car Rental Agency", "Alquiler De Coches" },
            { "Car Repair Agency", "Reparacion De Coches" },
            { "Car Wash Agency", "Lavado De Coches" },
            { "Electric Vehicle Charging Station", "Estacion De Carga De Vehiculos Electricos" },
            { "Gas Station", "Gasolinera" },
            { "Parking", "Estacionamiento" },
            { "Rest Stop", "Area De Descanso" },
            { "Farm", "Granja" },
            { "Art Gallery", "Galeria De Arte" },
            { "Museum", "Museo" },
            { "Performing Arts Theater", "Teatro De Artes Escenicas" },
            { "Library", "Biblioteca" },
            { "Preschool", "Preescolar" },
            { "Primary School", "Escuela Primaria" },
            { "Secondary School", "Escuela Secundaria" },
            { "University", "Universidad" },
            { "Amusement Center", "Centro De Entretenimiento" },
            { "Amusement Park", "Parque De Atracciones" },
            { "Aquarium", "Acuario" },
            { "Banquet Hall", "Salon De Banquetes" },
            { "Bowling Alley", "Bolera" },
            { "Casino", "Casino" },
            { "Community Center", "Centro Comunitario" },
            { "Convention Center", "Centro De Convenciones" },
            { "Cultural Center", "Centro Cultural" },
            { "Dog Park", "Parque Para Perros" },
            { "Event Venue", "Lugar De Eventos" },
            { "Hiking Area", "Zona De Senderismo" },
            { "Historical Landmark", "Monumento Historico" },
            { "Marina", "Marina" },
            { "Movie Rental", "Alquiler De Peliculas" },
            { "Movie Theater", "Cine" },
            { "National Park", "Parque Nacional" },
            { "Night Club", "Club Nocturno" },
            { "Park", "Parque" },
            { "Tourist Attraction", "Atraccion Turistica" },
            { "Visitor Center", "Centro De Visitantes" },
            { "Wedding Venue", "Lugar De Bodas" },
            { "Zoo", "Zoologico" },
            { "Accounting", "Contabilidad" },
            { "ATM", "Cajero Automatico" },
            { "Bank", "Banco" },
            { "American Restaurant", "Restaurante Americano" },
            { "Bakery", "Panaderia" },
            { "Bar", "Bar" },
            { "Barbecue Restaurant", "Restaurante De Barbacoa" },
            { "Brazilian Restaurant", "Restaurante Brasileno" },
            { "Breakfast Restaurant", "Restaurante De Desayuno" },
            { "Brunch Restaurant", "Restaurante De Brunch" },
            { "Cafe", "Cafeteria" },
            { "Chinese Restaurant", "Restaurante Chino" },
            { "Coffee Shop", "Cafe" },
            { "Fast Food Restaurant", "Restaurante De Comida Rapida" },
            { "French Restaurant", "Restaurante Frances" },
            { "Greek Restaurant", "Restaurante Griego" },
            { "Hamburger Restaurant", "Restaurante De Hamburguesas" },
            { "Ice Cream Shop", "Heladeria" },
            { "Indian Restaurant", "Restaurante Indio" },
            { "Indonesian Restaurant", "Restaurante Indonesio" },
            { "Italian Restaurant", "Restaurante Italiano" },
            { "Japanese Restaurant", "Restaurante Japones" },
            { "Korean Restaurant", "Restaurante Coreano" },
            { "Lebanese Restaurant", "Restaurante Libanes" },
            { "Meal Delivery", "Entrega De Comidas" },
            { "Meal Takeaway", "Comida Para Llevar" },
            { "Mediterranean Restaurant", "Restaurante Mediterraneo" },
            { "Mexican Restaurant", "Restaurante Mexicano" },
            { "Middle Eastern Restaurant", "Restaurante De Oriente Medio" },
            { "Pizza Restaurant", "Pizzeria" },
            { "Ramen Restaurant", "Restaurante De Ramen" },
            { "Restaurant", "Restaurante" },
            { "Sandwich Shop", "Tienda De Sandwiches" },
            { "Seafood Restaurant", "Restaurante De Mariscos" },
            { "Spanish Restaurant", "Restaurante Espanol" },
            { "Steak House", "Parrilla" },
            { "Sushi Restaurant", "Restaurante De Sushi" },
            { "Thai Restaurant", "Restaurante Tailandes" },
            { "Turkish Restaurant", "Restaurante Turco" },
            { "Vegan Restaurant", "Restaurante Vegano" },
            { "Vegetarian Restaurant", "Restaurante Vegetariano" },
            { "Vietnamese Restaurant", "Restaurante Vietnamita" },
            { "Administrative Area Level 1", "Area Administrativa Nivel 1" },
            { "Administrative Area Level 2", "Area Administrativa Nivel 2" },
            { "Country", "Pais" },
            { "Locality", "Localidad" },
            { "Postal Code", "Codigo Postal" },
            { "School District", "Distrito Escolar" },
            { "City Hall", "Ayuntamiento" },
            { "Courthouse", "Palacio De Justicia" },
            { "Embassy", "Embajada" },
            { "Fire Station", "Estacion De Bomberos" },
            { "Local Government Office", "Oficina De Gobierno Local" },
            { "Police", "Policia" },
            { "Post Office", "Oficina De Correos" },
            { "Dental Clinic", "Clinica Dental" },
            { "Dentist", "Dentista" },
            { "Doctor", "Doctor" },
            { "Drugstore", "Farmacia" },
            { "Hospital", "Hospital" },
            { "Medical Lab", "Laboratorio Medico" },
            { "Pharmacy", "Farmacia" },
            { "Physiotherapist", "Fisioterapeuta" },
            { "Spa", "Spa" },
            { "Bed And Breakfast", "Cama Y Desayuno" },
            { "Campground", "Campamento" },
            { "Camping Cabin", "Cabana De Camping" },
            { "Cottage", "Casa De Campo" },
            { "Extended Stay Hotel", "Hotel De Estancia Prolongada" },
            { "Farmstay", "Estancia En Granja" },
            { "Guest House", "Casa De Huespedes" },
            { "Hostel", "Hostal" },
            { "Hotel", "Hotel" },
            { "Lodging", "Alojamiento" },
            { "Motel", "Motel" },
            { "Private Guest Room", "Habitacion Privada" },
            { "Resort Hotel", "Hotel Resort" },
            { "RV Park", "Parque De Vehiculos Recreativos" },
            { "Church", "Iglesia" },
            { "Hindu Temple", "Templo Hindu" },
            { "Mosque", "Mezquita" },
            { "Synagogue", "Sinagoga" },
            { "Barber Shop", "Barberia" },
            { "Beauty Salon", "Salon De Belleza" },
            { "Cemetery", "Cementerio" },
            { "Child Care Agency", "Agencia De Cuidado Infantil" },
            { "Consultant", "Consultor" },
            { "Courier Service", "Servicio De Mensajeria" },
            { "Electrician", "Electricista" },
            { "Florist", "Floristeria" },
            { "Funeral Home", "Funeraria" },
            { "Hair Care", "Cuidado Del Cabello" },
            { "Hair Salon", "Salon De Belleza" },
            { "Insurance Agency", "Agencia De Seguros" },
            { "Laundry", "Lavanderia" },
            { "Lawyer", "Abogado" },
            { "Locksmith", "Cerrajero" },
            { "Moving Company", "Empresa De Mudanzas" },
            { "Painter", "Pintor" },
            { "Plumber", "Fontanero" },
            { "Real Estate Agency", "Agencia Inmobiliaria" },
            { "Roofing Contractor", "Contratista De Techo" },
            { "Storage", "Almacenamiento" },
            { "Tailor", "Sastre" },
            { "Telecommunications Service Provider", "Proveedor De Servicios De Telecomunicaciones" },
            { "Travel Agency", "Agencia De Viajes" },
            { "Veterinary Care", "Cuidado Veterinario" },
            { "Auto Parts Store", "Tienda De Repuestos De Auto" },
            { "Bicycle Store", "Tienda De Bicicletas" },
            { "Book Store", "Libreria" },
            { "Cell Phone Store", "Tienda De Telefonos Movil" },
            { "Clothing Store", "Tienda De Ropa" },
            { "Convenience Store", "Tienda De Conveniencia" },
            { "Department Store", "Gran Almacen" },
            { "Discount Store", "Tienda De Descuentos" },
            { "Electronics Store", "Tienda De Electronica" },
            { "Furniture Store", "Tienda De Muebles" },
            { "Gift Shop", "Tienda De Regalos" },
            { "Grocery Store", "Tienda De Comestibles" },
            { "Hardware Store", "Ferreteria" },
            { "Home Goods Store", "Tienda De Articulos Para El Hogar" },
            { "Home Improvement Store", "Tienda De Mejoras Para El Hogar" },
            { "Jewelry Store", "Joyeria" },
            { "Liquor Store", "Licoreria" },
            { "Market", "Mercado" },
            { "Pet Store", "Tienda De Mascotas" },
            { "Shoe Store", "Tienda De Zapatos" },
            { "Shopping Mall", "Centro Comercial" },
            { "Sporting Goods Store", "Tienda De Articulos Deportivos" },
            { "Store", "Tienda" },
            { "Supermarket", "Supermercado" },
            { "Wholesaler", "Mayorista" },
            { "Athletic Field", "Campo Atletico" },
            { "Fitness Center", "Gimnasio" },
            { "Golf Course", "Campo De Golf" },
            { "Gym", "Gimnasio" },
            { "Playground", "Parque Infantil" },
            { "Ski Resort", "Estacion De Esqui" },
            { "Sports Club", "Club Deportivo" },
            { "Sports Complex", "Complejo Deportivo" },
            { "Stadium", "Estadio" },
            { "Swimming Pool", "Piscina" },
            { "Airport", "Aeropuerto" },
            { "Bus Station", "Estacion De Autobuses" },
            { "Bus Stop", "Parada De Autobus" },
            { "Ferry Terminal", "Terminal De Ferry" },
            { "Heliport", "Heliopuerto" },
            { "Light Rail Station", "Estacion De Tranvia" },
            { "Park And Ride", "Aparcamiento Y Transbordo" },
            { "Subway Station", "Estacion De Metro" },
            { "Taxi Stand", "Parada De Taxis" },
            { "Train Station", "Estacion De Tren" },
            { "Transit Depot", "Deposito De Transporte" },
            { "Transit Station", "Estacion De Transito" },
            { "Truck Stop", "Parada De Camiones" }
        };

        public static string GetTraduccion(string tipo)
        {
            if (Tipos.ContainsKey(tipo))
            {
                return Tipos[tipo];
            }
            else
            {
                return "Tipo no encontrado";
            }
        }
    }
}
